name: sunshine
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  queries: "^0.0.15"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/img/parisback.png
    - assets/img/bottom_parisback.png
    - assets/img/dotEmpty.png
    - assets/img/dotBlueishFull.png
    - assets/img/d1s.png
    - assets/img/d2s.png
    - assets/img/d3s.png
    - assets/img/d4s.png
    - assets/img/d5s.png
    - assets/img/d6s.png
    - assets/img/d7s.png
    - assets/img/d8s.png
    - assets/img/d9s.png
    - assets/img/n1s.png
    - assets/img/n2s.png


  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.

  # To add assets from package dependencies, first ensure the asset
  # is in the lib/ directory of the dependency. Then,
  # refer to the asset with a path prefixed with
  # `packages/PACKAGE_NAME/`. The `lib/` is implied, do not
  # include `lib/` in the asset path.
  #
  # Here is an example:
  #
  # assets:
  #  - packages/PACKAGE_NAME/path/to/asset

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
